# Dependabot configuration for this project:
# - Weekly updates are scheduled to balance timely security/bug fixes with minimal disruption to development.
# - All npm dependencies in the root directory are monitored.
# - Please coordinate major dependency upgrades with the team to ensure compatibility and stability.

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
